### ISSUE TITLE
install kingfisher on m1 MacBook Pro

### ISSUE THREAD

**Issue by Guanxin1996** [wwood/kingfisher-download#16]
when I use the code conda env create -n kingfisher -f kingfisher.yml on my m1 Mac, the error occurs
Solving environment: failed

ResolvePackageNotFound: 
  - aria2[version='>=1.36.0']
  - sra-tools
  - sracat
I can't install this three packages using conda.

**Comment by wwood** [comment]
Hi,

Thanks for your interest. Fixing those might be straightforward, I'm not sure - I don't have much experience with m1. All I can say is that it is possible to use some parts of kingfisher without those packages (in particular, you should be able to download from ENA if you specify threads 1 so kingfisher uses curl rather than aria2).

kingfisher annotate should work also.

**Comment by Guanxin1996** [comment]
Thank you for your answer. I give up using it on M1. However，kingfisher helps me a lot on linux.i would recommend it to many others.
Thank you so much for helping me again.

**Comment by wwood** [comment]
OK, disappointing to hear that didn't work out. Thanks for getting back to me.
