### ISSUE TITLE
How split files in Kingfisher get download process?

### ISSUE THREAD

**Issue by GuohuaZhu** [wwood/kingfisher-download#24]
Thanks for your wonderful contribution.
 I have some problems, for example, when I download single-cell sra data which were pair-ends, kingfisher will automatically convert it into a single fastq file, while I need to split it into three fastq files. 
However, I canno't find the corresponding setting parameters in kingfisher with spilt-files that fastq-dump provided, could you help me to solve this problem?

Sincerely

**Comment by wwood** [comment]
Hi,

I'm a bit surprised it converts it to a single fastq file. This seems to me as if there is a bug in kingfisher or the data is not stored as paired at NCBI. What is the accession you are having problems with?

Also, to be clear, which parameters do you mean when you say

> the corresponding setting parameters in kingfisher with spilt-files that fastq-dump provided

As a workaround you can try downloading as a .sra file (`-f sra`) and then run fastq-dump / fasterq-dump manually.

Thanks, ben

**Comment by GuohuaZhu** [comment]
Thanks for your kindly reply,  
the code  I had used as follow:

kingfisher get -r  SRR17165223 -m ena-ascp ena-ftp prefetch aws-http ; 

I didn't know how to set setting parameters in kingfisher with spilt-files that fastq-dump provided, could you help me

**Comment by wwood** [comment]
Hi,

Thanks. I think the issue here isn't kingfisher but the way that the data are stored on ENA. On SRA they are 3 reads per spot, but ENA only has a single fastq file. Since you are downloading from ENA you just get one file.

I would suggest downloading from SRA using e.g. `-m prefetch -f fastq.gz` - that will then run fasterq-dump and should result in 3 files. 

Let me know how you go.
ben
